title: United Fronteras
email: unitedfronteras@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The mission of this project is to bring together active and inactive works that leverage digital components to document the borderlands from multiple perspectives (literature, archives, art, oral histories, music, among others) from the nineteenth to the twenty-first century. The projects are featured through a digital map and various visualizations that offer audiences a unique opportunity to meaningfully engage in the multi-dimensional layers of border spaces through multi-disciplinary, institutional, community-based, and individual collaborations. This platform also establishes and maintains a digital record of projects that encompass the borderlands.

baseurl: "/unitedfronteras"
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  sferna

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
