# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: United Fronteras
email: unitedfronteras@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The mission of this project is to bring together active and inactive works that leverage digital components to document the borderlands from multiple perspectives (literature, archives, art, oral histories, music, among others) from the nineteenth to the twenty-first century. The projects are featured through a digital map and various visualizations that offer audiences a unique opportunity to meaningfully engage in the multi-dimensional layers of border spaces through multi-disciplinary, institutional, community-based, and individual collaborations. This platform also establishes and maintains a digital record of projects that encompass the borderlands.

baseurl: "/unitedfronteras"
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  sferna

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
